on:
  push:
    branches: [ "main", "master" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main", "master" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get commit SHA
        id: commit_sha
        run: echo "::set-output name=sha::$(echo ${GITHUB_SHA})"

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2.4.1

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4.3.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Convert IMAGE_NAME to lowercase
        id: image_name_lowercase
        run: echo "::set-output name=image_name_lowercase::$(echo ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} | tr '[:upper:]' '[:lower:]')"

      - name: Determine Tags
        id: tags
        run: |
          echo "::set-output name=version_tag::${{ steps.image_name_lowercase.outputs.image_name_lowercase }}:${{ steps.commit_sha.outputs.sha }}"
          if [[ "${{ github.ref_name }}" == "main" || "${{ github.ref_name }}" == "master" || "${{ github.ref }}" == refs/tags/v*.*.* ]]; then
            echo "::set-output name=latest_tag::${{ steps.image_name_lowercase.outputs.image_name_lowercase }}:latest"
          else
            echo "::set-output name=latest_tag::"
          fi

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ steps.tags.outputs.version_tag }}
            ${{ steps.tags.outputs.latest_tag }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            COMMIT_SHA=${{ steps.commit_sha.outputs.sha }}
            IMAGE_NAME=${{ steps.image_name_lowercase.outputs.image_name_lowercase }}:${{ steps.commit_sha.outputs.sha }}

