name: Check setup.py Update

on:
  pull_request:
    branches: [ "main", "master" ]
    paths: 
      - 'setup.py'  # Trigger the workflow only if setup.py is modified

jobs:
  check-setup-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check for setup.py changes
        id: check_changes
        run: |
          git fetch origin ${{ github.base_ref }}
          git diff --name-only origin/${{ github.base_ref }}...${{ github.sha }} | grep setup.py
          if [ $? -ne 0 ]; then
            echo "::error::setup.py must be updated in every PR to the main/master branch."
            exit 1
          else
            echo "setup.py has been updated."
          fi

      - name: Success message
        run: echo "Check completed successfully, setup.py is updated."

